language: node_js
# gulp-jasmine-phantom requires node 0.12 or higher 
# for the execSync function
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
  - npm install -g gulp-jshint
  - npm install -g phantomjs
  - npm install -g jasmine
  - npm install -g gulp-jasmine-phantom
script: gulp